#:kivy 1.9.1

<MenuScreen>:
    name: 'menu'
    
    BoxLayout:
        orientation: 'horizontal'
            
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Load Map'
            Button:
                text: 'Save Map'
            Button:
                text: 'Generate Map'
            Button:
                text: 'Enter Map'
        BoxLayout:
            Image:
                source: 'ss2.png'